Symphony Limited/Controllers/ExamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Symphony_Limited.Data;
using Symphony_Limited.Models;

namespace Symphony_Limited.Controllers
{
    public class ExamController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ExamController(ApplicationDbContext context) { 

            _context = context;
        
        }

        public async Task<IActionResult> AllExams()
        {
            var examinations = await _context.Examinations.ToListAsync();
            return View(examinations);
        }
        public IActionResult AddExam()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddExam(Examination examination)
        {
            if (ModelState.IsValid)
            {
                await _context.Examinations.AddAsync(examination);
                _context.SaveChanges();
                return RedirectToAction("AllExams");
            }
            return View(examination);
        }


        public async Task<IActionResult> EditExam(int id)
        {
            var examination = await _context.Examinations.FindAsync(id);
            if (examination == null)
            {
                return NotFound();
            }
            return View(examination);
        }

        [HttpPost]
        public async Task<IActionResult> EditExam(Examination examination)
        {
            if (ModelState.IsValid)
            {
                _context.Examinations.Update(examination);
                await _context.SaveChangesAsync();
                return RedirectToAction("AllExams");
            }
            return View(examination);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteExam(int id)
        {
            var examination = await _context.Examinations.FindAsync(id);
            if (examination != null)
            {
                _context.Examinations.Remove(examination);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("AllExams");
        }
    }
}

Symphony Limited/Views/Exam/AddExam.cshtml
@model Symphony_Limited.Models.Examination;
@{
	Layout = "~/Views/shared/_LayoutDashboard.cshtml";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add Exam</h4>
                        <p class="card-description">
                            Basic form elements
                        </p>
                        <form class="forms-sample"  method="post">
                            <div class="form-group">
                                <label for="exampleInputName1">Exam Name</label>
                                <input type="text" class="form-control" asp-for="ExamName" id="exampleInputName1" placeholder="Enter Course Name">
                            </div>
                            <div class="form-group">
                                <label for="exampleTextarea1">Exam Date</label>
                                <input type="date" class="form-control" asp-for="ExamDate" id="exampleTextarea1">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword4">Fees</label>
                                <input type="text" class="form-control" asp-for="Fees" id="exampleInputPassword4" placeholder="Duration">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputCity1">Created At</label>
                                <input type="date" class="form-control" asp-for="Created_at" id="exampleInputCity1" placeholder="Created At">
                            </div>
                            <input type="submit" class="btn btn-primary mr-2" value="Add Exam" />
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Symphony Limited/Views/Exam/AllExams.cshtml
@model IEnumerable<Examination>
@{
    Layout = "~/Views/shared/_LayoutDashboard.cshtml";
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">All Exams</h4>
                        <p class="card-description">
                            <a asp-controller="Exam" asp-action="AddExam">Add new exam</a>
                        </p>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Exam Id</th>
                                        <th>Exam Name</th>
                                        <th>Exam Date</th>
                                        <th>Exam Fees</th>
                                        <th>Created At</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                    @foreach (var examination in Model)
                                        {
                                            <tr>

                                            <td>@examination.ExamId</td>
                                            <td>@examination.ExamName</td>
                                            <td>@examination.ExamDate</td>
                                            <td>@examination.Fees</td>
                                            <td>@examination.Created_at</td>
                                            <td>
                                                <a class="btn btn-outline-primary" asp-controller="Exam" asp-action="EditExam" asp-route-id="@examination.ExamId">Edit</a>
                                                <form class="mt-3" method="post">
                                                    <button class="btn btn-outline-danger" type="submit" asp-controller="Exam" asp-action="DeleteExam" asp-route-id="@examination.ExamId">Delete</button>
                                                </form>
                                            </td>
										</tr>
                                        }
                                    
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Symphony Limited/Views/Exam/EditExam.cshtml
@model Examination
@{
	Layout = "~/Views/shared/_LayoutDashboard.cshtml";
}

<div class="main-panel">
<div class="content-wrapper">
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Update Exam</h4>
                    
                    <form class="forms-sample" method="post">
                            <input type="hidden" class="form-control" asp-for="ExamId">
                        <div class="form-group">
                            <label for="exampleInputName1">Exam Name</label>
                            <input type="text" class="form-control" asp-for="ExamName" id="exampleInputName1" placeholder="Enter Exam Name">
                        </div>
                        <div class="form-group">
                            <label for="exampleTextarea1">Exam Date</label>
                            <input type="date" class="form-control" asp-for="ExamDate" id="exampleTextarea1">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword4">Fees</label>
                            <input type="text" class="form-control" asp-for="Fees" id="exampleInputPassword4" placeholder="Fees">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputCity1">Created At</label>
                            <input type="date" class="form-control" asp-for="Created_at" id="exampleInputCity1" placeholder="Created At">
                        </div>
                        <input type="submit" class="btn btn-primary mr-2" value="Update Exam" />
                        <button class="btn btn-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>